apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: {{ or .DNSServiceIP .DNSServiceIPv6 }}
  clusterIPs:
  {{- if .DNSServiceIP }}
    - {{ .DNSServiceIP }}
  {{- end }}
  {{- if .DNSServiceIPv6 }}
    - {{ .DNSServiceIPv6 }}
  {{- end }}
  ipFamilies:
  {{- if .DNSServiceIP }}
    - IPv4
  {{- end }}
  {{- if .DNSServiceIPv6 }}
    - IPv6
  {{- end }}
  {{- if and .DNSServiceIP .DNSServiceIPv6 }}
  ipFamilyPolicy: RequireDualStack
  {{- else }}
  ipFamilyPolicy: SingleStack
  {{- end }}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
