apiVersion: v1
kind: Service
metadata:
  labels:
    component: apid
    provider: talos
  name: {{ .KubernetesTalosAPIServiceName }}
  namespace: {{ .KubernetesTalosAPIServiceNamespace }}
spec:
  ports:
  - name: apid
    port: {{ .ApidPort }}
    protocol: TCP
    targetPort: {{ .ApidPort }}
